[server]
# Maximum size in megabytes for files uploaded with the file_uploader
maxUploadSize = 200

# If false, will attempt to open a browser window on start
headless = true

# Enables support for Cross-Origin Resource Sharing (CORS)
enableCORS = false

# Enables end-to-end encryption with your Streamlit app
enableXsrfProtection = true

[browser]
# Internet address where users should point their browsers in order to connect to the app
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit
gatherUsageStats = false

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'
level = "info"

[client]
# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not draw to a Streamlit app
showErrorDetails = true

[runner]
# Allows you to type --runner.magicEnabled 0 to disable magic commands
magicEnabled = true

# Stops command line parameters from being sent to Streamlit
fastReruns = true

[theme]
# Primary accent color for interactive elements
primaryColor = "#67340fff"

# Background color for the main content area
backgroundColor = "#f7f5f3ff"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#6d3a00ff"

# Color used for almost all text
textColor = "#010116ff"

# Font family for all text in the app, except code blocks
font = "sans serif"